# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf8367953f322dbfd4472762048f147a496a3a4c1f2d214da6fe3098a71e7e653bf8ce2d66ba29e5cd79ea93502630b1113448e57a1ba717d3782793cc317066

test:
  secret_key_base: 6c6518cc465dc9a66357f127c7436582d1e03270dd0b6c087bb3299f9317fceacde9efcf75ce6b381dfc3ead701f0774eb29ebb4a584b51555297e33245ff5c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
